version: "3.9"
services:
  ui:
    build: frontend/
    environment: 
      - REACT_APP_API=http://localhost:5000/api/
    ports:
      - '8080:8080'
    links:
      - api
  api:
    build: api/
    environment: 
        - MONGO_URL=mongodb://mongo:27017/
        - DB_NAME=gateways
        - PORT=5000
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"